server:
  port: 8189
  servlet:
    context-path: /app
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:postgres
    username: postgres
    password: telefon290787
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
  flyway:
    baseline-on-migrate: true
